[features]
seeds = false
[programs.localnet]
solanaloans = "Em8pj36RxaefZ2cm9ZfcnyXedyemqbDVgTbGGcQMae5A"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/lukeqin/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
