[features]
seeds = false
[programs.localnet]
# solanaloans = "BBZ2HBi6WbaFtGeXwewBbMe3x4foTcrQNfc4jJUPLt8a"
solanaloans = "AVpdKDSQo8PzSV5zDspNVGCJcwBwm21zzTGDm8vKiw8z"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/vaibhav.mallya/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
